<?php

 // PROGRAMMATION ORIENTEE OBJET 
 // AIDER A REPRESENTER DONNEES DE MANIERE PLUS CONCRETE EN REGROUPANT LES INFOS DANS UNE CLASSE 
 // ET UTILISER CES CLASSES DANS LE CODE; CHAQUE CLASSE SERA COMME UNE BRIQUE LOGICIEL UTILISEE POUR CONSTRUIRE
 
class Tweet {
public $pseudo;
public $message;
public $date;
public $retweet;
public $photo;
public $like;
}


?>